version: '3.7'
services:
  californianhealthcalendarapi:
    image: californianhealthcalendarapi
    container_name: ch-api-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "5000:80"
    
